//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public int PersonnelID { get; set; }
        public int AttendanceSetID { get; set; }
        public Nullable<int> Counts { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
    
        public virtual AttendanceSet AttendanceSet { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
