//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoneyManageEntities2 : DbContext
    {
        public MoneyManageEntities2()
            : base("name=MoneyManageEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Attendances> Attendances { get; set; }
        public virtual DbSet<AttendanceSet> AttendanceSet { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<GetPrize> GetPrize { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<Prize> Prize { get; set; }
        public virtual DbSet<Ranks> Ranks { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<Subsidy> Subsidy { get; set; }
        public virtual DbSet<Subsidynotes> Subsidynotes { get; set; }
    }
}
