//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int ID { get; set; }
        public int PersonnelID { get; set; }
        public string PersonnelName { get; set; }
        public string ShopName { get; set; }
        public string RankName { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> Basepay { get; set; }
        public Nullable<int> AttendanceDebits { get; set; }
        public Nullable<int> SubMoney { get; set; }
        public Nullable<decimal> PrizeMoney { get; set; }
        public Nullable<int> Payables { get; set; }
        public Nullable<int> Paidwages { get; set; }
        public string Remarks { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
