//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;

    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Attendances = new HashSet<Attendances>();
            this.GetPrize = new HashSet<GetPrize>();
            this.Pay = new HashSet<Pay>();
            this.Subsidynotes = new HashSet<Subsidynotes>();
        }
        public int ID { get; set; }
        
        //[Required(ErrorMessage ="密码不能为空")]
        public Nullable<int> Pwd { get; set; }

        //[Required(ErrorMessage = "姓名不能为空")]
        public string Name { get; set; }
        public Nullable<int> States { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> Sex { get; set; }

        //[Required(ErrorMessage = "地域不能为空")]
        public string Addresses { get; set; }
        //[Required]
        public Nullable<int> Photo { get; set; }
        public Nullable<int> ShopID { get; set; }

        //[Required(ErrorMessage = "邮箱不能为空")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendances> Attendances { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GetPrize> GetPrize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay> Pay { get; set; }
        public virtual Ranks Ranks { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subsidynotes> Subsidynotes { get; set; }
    }
}
